### ISSUE TITLE
heroku-deflater overwrites production.rb cache-control setting

### ISSUE THREAD

**Issue by briank-musichouse** [romanbsd/heroku-deflater#31]
in config/environments/production.rb, I have the following code:
`config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=31536000' }`

However, any compressed .js and .css files coming from my Rails app are being served with the header value `public, max-age=86400`. It appears this gem is overriding the value explicitly set within my app.

**Comment by dskoziol** [comment]
I just ran into this bug. It would be great if you could update the gem for it now that it's been merged!

**Comment by dskoziol** [comment]
@dylanfisher I'm using the "fixed" version of this in an app, but my resources are still being cached for 24 hours rather than the 1 year set in my production.rb. Is it possible that this issue wasn't fixed by your commit?

**Comment by brian-kephart** [comment]
@dylanfisher are you serving assets via a CDN? If so, have you requested the assets from the webserver via curl?

Since the fix, I'm still seeing the wrong headers in my browser. At first I thought the gem was still buggy, but curl shows them being served correctly from my website, meaning the problem lies elsewhere.

**Comment by dylanfisher** [comment]
I only tested this locally, haven't tried with a CDN yet. 

Maybe the CDN is returning cached content that was created with the old headers?

**Comment by Deathis** [comment]
https://github.com/romanbsd/heroku-deflater/blob/master/lib/heroku-deflater/railtie.rb#L17
